controversies_end/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('adminofsidelionsogang&ducksungssis/', admin.site.urls),
    path('', include("polls.urls")),
]

polls/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [

    path('', start_page, name = "start_page"),

    path('main_page', main_page, name = "main_page"),

    path('vote_page', vote_page, name = "vote_page"),

    path('vote/result', vote, name = "vote"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/models.py
from django.db import models
from django.utils import timezone

class Vote(models.Model):
    vote_name = models.CharField(default = '',max_length=20)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.vote_name

class Choice(models.Model):
    vote = models.ForeignKey(Vote,on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    count = models.IntegerField(default=0)
    powerful = models.BooleanField(default=False)
    def __str__(self):
        return self.name

polls/forms.py
from django.forms.models import ModelForm
from django import forms
from .models import Vote, Choice

class Voteform(ModelForm):
    class Meta:
        model = Vote
        fields = ['vote_name']

class Choiceform(ModelForm):
    class Meta:
        model = Choice
        fields = ['name', 'count', 'powerful']


polls/views.py
from django.shortcuts import render
from .models import *

total_question_number = 10 # 총 질문의 갯수


def is_powerful(opt1, opt2) :
    # 1번과 2번이 같으면 -1 반환
    if (opt1.count == opt2.count) :
        opt1.powerful=True
        opt2.powerful=True
        opt1.save()
        opt2.save()
        return -1

    # 1번이 2번보다 많으면 1 반환
    elif (opt1.count > opt2.count) :
        opt1.powerful = True
        opt2.powerful = False
        opt1.save()
        opt2.save() 
        return 1
    
    # 1번이 2번보다 작으면 0 반환
    else :
        opt1.powerful = False
        opt2.powerful = True
        opt1.save()
        opt2.save()
    return 0


def start_page(request) :
    total_voted_number = Choice.objects.get(id=1).count +Choice.objects.get(id=2).count # 총 투표한 사람들의 수
    return render(request, 'index.html', {'total_voted_number' : total_voted_number })


def main_page(request) :
    total_voted_number = Choice.objects.get(id=1).count +Choice.objects.get(id=2).count # 총 투표한 사람들의 수
    vote = Vote.objects.all()
    choice = Choice.objects.all()
    return render(request, 'main.html', {'vote':vote, 'choice':choice, 'total_voted_number' : total_voted_number })


def vote_page(request) :
    """
    투표 페이지로 가는 뷰
    """
    vote = Vote.objects.all()
    total_voted_number = Choice.objects.get(id=1).count +Choice.objects.get(id=2).count # 총 투표한 사람들의 수

    return render(request, 'vote.html', {'vote':vote, 'total_voted_number' : total_voted_number })


def vote(request):
    """
    1) 투표한 항목들 값 갱신
    2) 주류항목인 애들 골라서 powerful=1 로 필드값 설정
    3) 유저가 선택한 항목에서 주류 갯수 따라서 result 값 반환 
    """
    if request.method == "GET":

        # 1) 투표한 항목들 값 갱신

        voted_choice_id = []
        for j in range(1,total_question_number+1) :
            voted_choice_id.append(int(request.GET[f'choice{j}']))

        for i in voted_choice_id :
            voted_choice = Choice.objects.get(id=i)
            voted_choice.count+=1 # 내 선택 반영
            voted_choice.save()

        #2) 주류 항목인 애들 고르기& 유저가 택한 값 중에서 주류인 것 판별 (user_type으로 주류 선택한 것 갯수)

        user_type = 0
        for k in range(1, total_question_number*2,2) :
            powerful = is_powerful(Choice.objects.get(id=k), Choice.objects.get(id=k+1))

            # k번 > k+1번 : k번이 주류
            if (powerful == 1):
                if (voted_choice_id[k//2] == k): # 내 선택이 k일 때
                    user_type += 1

            # k번 < k+1번 : k+1번이 주류
            elif (powerful == 0):
                if (voted_choice_id[k//2] == k+1): # 내 선택이 k+1일 때
                    user_type += 1

            # k번 = k+1번 : 둘다 주류
            else:
                user_type += 1 # 내 선택에 상관없이

        #3) user_type (주류 갯수 고른 것) 따라서 type 정해줌 (총 4 type 종류 있음)

        if user_type <= 1 :
            user_type_num = 1
        elif user_type <= 4 :
            user_type_num = 2
        elif user_type <= 7 :
            user_type_num = 3
        else : user_type_num = 4

        #4) 내가 선택한 아이디값

        final_choice_list=[]
        id_list=[]

        for i in voted_choice_id:
            final_choice_list.append(Choice.objects.get(id=i))
            id_list.append(i)
        print(id_list)
        return render(request, 'vote_result.html', {'type_pk':user_type_num, 'user_type':user_type, 'final_choice_list' : final_choice_list,"id_list":id_list})

polls/templates/index.html
{% load static %}
<!--링크 클릭하자 마자 보이는 화면-->
<html>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2196391253962038"
    crossorigin="anonymous"></script>
    <head>
        <link href="https://images.velog.io/images/myway00/post/ea055d2f-8da9-408b-85e6-ac9edf4eff37/favicon.ico" rel="shortcut icon" type="image/x-icon">
        <link href="static/css/start.css?after" type="text/css" rel="stylesheet">
        <link href="static/css/style.css" type="text/css" rel="stylesheet">  
        <script src="https://kit.fontawesome.com/105dacfb44.js" crossorigin="anonymous"></script>
    </head>

    <body onload="voteCheck()">
        <div>

        <div class="nav">
            <div class="ad3" style="text-align:center">
                <ins class="kakao_ad_area" style="display:none;" 
                data-ad-unit    = "DAN-1AWNpxec4lVO6WlX" 
                data-ad-width   = "320" 
                data-ad-height  = "50"></ins> 
               <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
            </div>
            <a href="{% url 'start_page' %}">
                <img src="{% static 'images/logo3.png' %}" width="240px" ; height="95px" ;>
        </div>
        <div class="total_voted_num" style="display:none;">
            {{total_voted_number}}
        </div>
        <div class="total_voted_number" value="{{total_voted_number}}">
            <!--현재 투표한 인원나타낼 div-->
        </div>
        <div class="count_num"></div>
        <br>
        <div class="image blinking">
            <img src="/static/images/logo3.png" class="logo" alt="No image" width="800px">
        </div>
        <br>
        <div class = "voteimpossible" style="    text-shadow: 2px 2px 6px #c9c9c9;
        color:#faff00;">투표는 하루에 한번만 가능합니다.</div>
        <div class="votepossible">
            <div class="box" id="vote">
                <a href="{% url 'vote_page' %}">
                    <h1>투표하러 가기</h1>
                </a>
            </div>
        </div>
        <div class="box" id="new">
            <a href="{% url 'main_page' %}">
                <h1>실시간 투표 현황 보러가기</h1>
            </a>
        </div>

        <br>
    </div>

</body>
    </body>
    <footer style="text-align: center; color:rgb(72, 72, 60);">
        © 2022 sogangsisters@gmail.com<br>
        <a href="https://www.instagram.com/likelion_sg"><img src="/static/images/sg.png" style="color: darkgray;" width="50"
                height="50"></a>
    
        <a href="https://www.instagram.com/likelion_ds"><img src="/static/images/ds.png" width="50" height="50"></a>
    
        <br><br><br>
        <div class="ad1" style="text-align: center;">
            <ins class="kakao_ad_area" style="display:block;" data-ad-unit="DAN-K1ONl6gS9BoFHEkW" data-ad-width="320"
                data-ad-height="50"></ins>
            <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
        </div>
        <div class="ad2" style="text-align:center">
            <ins class="kakao_ad_area" style="display:block;" data-ad-unit="DAN-xdRWH6H61jxWboHL" data-ad-width="320"
                data-ad-height="50"></ins>
            <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
        </div>


    </footer>

</html>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
    console.log(getCookie("isVoted"))

    // 쿠키 가져오는 함수
    function getCookie(cookieName) {
        var cookieValue = null;
        if (document.cookie) {
            var array = document.cookie.split((escape(cookieName) + '='));
            if (array.length >= 2) {
                var arraySub = array[1].split(';');
                cookieValue = unescape(arraySub[0]);
            }
        }
        return cookieValue;
    }
    // 투표 판별, 했으면 true, 안했으면 false
    window.onload =function voteCheck() {
        var voting = document.getElementsByClassName("votepossible")[0];
        var voted = document.getElementsByClassName("voteimpossible")[0];
        if (getCookie("isVoted") == null) {
            //투표 가능하도록
            voting.style.display = 'block';
            voted.style.display = 'none';
            console.log("재투표가능");
        } else {
            voting.style.display = 'none';
            voted.style.display = 'block';
            console.log("재투표불가");
        }
    } 
var today = new Date();

var year = today.getFullYear();
var month = ('0' + (today.getMonth() + 1)).slice(-2);
var day = ('0' + today.getDate()).slice(-2);

var dateString = year + '년 ' + month  + '월' + day + "일";

voted_num = document.getElementsByClassName("total_voted_num")[0].innerHTML

var defaulttxt = " 누적 투표인원은 "
// var text = "my line1 \nMyline 2";
// $('#dialog').html(text.replace("\n", "<br>"));

$({ val : 0 }).animate({ val : voted_num }, {
    duration: 1500,
    step: function() {
      var num = numberWithCommas(Math.floor(this.val));
      $(".total_voted_number").text(dateString+defaulttxt + num + "명입니다.");
    },
    complete: function() {
      var num = numberWithCommas(Math.floor(this.val));
      $(".total_voted_number").text(dateString+defaulttxt + num + "명입니다.");
    }
  });
  
  function numberWithCommas(x) {
      return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }
var today = new Date();
var year = today.getFullYear();
var month = ('0' + (today.getMonth() + 1)).slice(-2);
var day = ('0' + today.getDate()).slice(-2);

var dateString = year + '년' + month  + '월' + day + "일";

</script>

polls/templates/main.html
{% load static %}
<html>
<head>
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2196391253962038"
     crossorigin="anonymous"></script>

    <link href="https://images.velog.io/images/myway00/post/ea055d2f-8da9-408b-85e6-ac9edf4eff37/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <link href="static/css/main.css" type="text/css" rel="stylesheet">  
    <link href="static/css/style.css" type="text/css" rel="stylesheet">  
    <script src="https://kit.fontawesome.com/105dacfb44.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
</head>
<body style="background-color: black;">
    <div class="logo">
        <a href="{% url 'start_page' %}">
            <img src="{% static 'images/logo3.png' %}" width="240px" ; height="95px"; >
        </a>
    </div>

    <div>
        <h1 class="new">실시간 투표 현황
    </div>
    <div class="all">
        <div class="graph">
            <span class="option1" id="1">{{vote.0.choice_set.all.0}}</span>
            <span class="option2" id="2">{{vote.0.choice_set.all.1}}<span class="p"></span></span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="3">{{vote.1.choice_set.all.0}}</span>
            <span class="option2" id="4">{{vote.1.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="5">{{vote.2.choice_set.all.0}}</span>
            <span class="option2" id="6">{{vote.2.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="7">{{vote.3.choice_set.all.0}}</span>
            <span class="option2" id="8">{{vote.3.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="9">{{vote.4.choice_set.all.0}}</span>
            <span class="option2" id="10">{{vote.4.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="11">{{vote.5.choice_set.all.0}}</span>
            <span class="option2" id="12">{{vote.5.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="13">{{vote.6.choice_set.all.0}}</span>
            <span class="option2" id="14">{{vote.6.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="15">{{vote.7.choice_set.all.0}}</span>
            <span class="option2" id="16">{{vote.7.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="17">{{vote.8.choice_set.all.0}}</span>
            <span class="option2" id="18">{{vote.8.choice_set.all.1}}</span>
        </div>
        <br>
        <div class="graph">
            <span class="option1" id="19">{{vote.9.choice_set.all.0}}</span>
            <span class="option2" id="20">{{vote.9.choice_set.all.1}}</span>
        </div>
        <!-- <img class="reset" src="static/images/reset.png" style="cursor:pointer" width=80px; onClick="window.location.reload()"> -->
        <i style="cursor:pointer;color:rgb(0, 0, 0)" onClick="window.location.reload()" class="fa-solid fa-rotate fa-4x "></i>
        <!-- <i   class="fa fa-refresh fa-spin fa-fw"></i>   -->
    </div>  
<br>
<br>


<br><br>
</body>
<footer style="text-align: center; color: rgb(72, 72, 60);">
    ©2022 sogangsisters@gmail.com<br>
    <a href = "https://www.instagram.com/likelion_sg"><img src="/static/images/sg.png" style="color: darkgray;" width="50" height="50"></a>
    <a href = "https://www.instagram.com/likelion_ds"><img src="/static/images/ds.png"  width="50" height="50"></a>
    <br><br><br>
    <div class = "ad1" style="text-align: center;">
        <ins class="kakao_ad_area" style="display:block;" 
        data-ad-unit    = "DAN-K1ONl6gS9BoFHEkW" 
        data-ad-width   = "320" 
        data-ad-height  = "50"></ins> 
        
        <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
    </div>
    <div class="ad2" style="text-align:center">
        <ins class="kakao_ad_area" style="display:none;" data-ad-unit="DAN-xdRWH6H61jxWboHL" data-ad-width="320"
            data-ad-height="50"></ins>
        <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
    </div>
    <div class="ad3" style="text-align:center">
        <ins class="kakao_ad_area" style="display:none;" 
        data-ad-unit    = "DAN-1AWNpxec4lVO6WlX" 
        data-ad-width   = "320" 
        data-ad-height  = "50"></ins> 
       <script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
    </div>
</footer>
</html>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
    $("#1").width("{{vote.0.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#2").width("{{vote.0.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#3").width("{{vote.1.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#4").width("{{vote.1.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#5").width("{{vote.2.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#6").width("{{vote.2.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#7").width("{{vote.3.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#8").width("{{vote.3.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#9").width("{{vote.4.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#10").width("{{vote.4.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#11").width("{{vote.5.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#12").width("{{vote.5.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#13").width("{{vote.6.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#14").width("{{vote.6.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#15").width("{{vote.7.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#16").width("{{vote.7.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#17").width("{{vote.8.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#18").width("{{vote.8.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    $("#19").width("{{vote.9.choice_set.all.0.count}}" / "{{total_voted_number}}" * 100 + "%");
    $("#20").width("{{vote.9.choice_set.all.1.count}}" / "{{total_voted_number}}" * 100 + "%");

    document.getElementById("1").innerHTML = "{{vote.0.choice_set.all.0}}"+" ( "+("{{vote.0.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.0.choice_set.all.0.count}}표"
    document.getElementById("2").innerHTML = "{{vote.0.choice_set.all.1}}"+" ( "+("{{vote.0.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.0.choice_set.all.1.count}}표"
    document.getElementById("3").innerHTML = "{{vote.1.choice_set.all.0}}"+" ( "+("{{vote.1.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.1.choice_set.all.0.count}}표"
    document.getElementById("4").innerHTML = "{{vote.1.choice_set.all.1}}"+" ( "+("{{vote.1.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.1.choice_set.all.1.count}}표"
    document.getElementById("5").innerHTML = "{{vote.2.choice_set.all.0}}"+" ( "+("{{vote.2.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.2.choice_set.all.0.count}}표"
    document.getElementById("6").innerHTML = "{{vote.2.choice_set.all.1}}"+" ( "+("{{vote.2.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.2.choice_set.all.1.count}}표"
    document.getElementById("7").innerHTML = "{{vote.3.choice_set.all.0}}"+" ( "+("{{vote.3.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.3.choice_set.all.0.count}}표"
    document.getElementById("8").innerHTML = "{{vote.3.choice_set.all.1}}"+" ( "+("{{vote.3.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.3.choice_set.all.1.count}}표"
    document.getElementById("9").innerHTML = "{{vote.4.choice_set.all.0}}"+" ( "+("{{vote.4.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.4.choice_set.all.0.count}}표"
    document.getElementById("10").innerHTML = "{{vote.4.choice_set.all.1}}"+" ( "+("{{vote.4.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.4.choice_set.all.1.count}}표"
    document.getElementById("11").innerHTML = "{{vote.5.choice_set.all.0}}"+" ( "+("{{vote.5.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.5.choice_set.all.0.count}}표"
    document.getElementById("12").innerHTML = "{{vote.5.choice_set.all.1}}"+" ( "+("{{vote.5.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.5.choice_set.all.1.count}}표"
    document.getElementById("13").innerHTML = "{{vote.6.choice_set.all.0}}"+" ( "+("{{vote.6.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.6.choice_set.all.0.count}}표"
    document.getElementById("14").innerHTML = "{{vote.6.choice_set.all.1}}"+" ( "+("{{vote.6.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.6.choice_set.all.1.count}}표"
    document.getElementById("15").innerHTML = "{{vote.7.choice_set.all.0}}"+" ( "+("{{vote.7.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.7.choice_set.all.0.count}}표"
    document.getElementById("16").innerHTML = "{{vote.7.choice_set.all.1}}"+" ( "+("{{vote.7.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.7.choice_set.all.1.count}}표"
    document.getElementById("17").innerHTML = "{{vote.8.choice_set.all.0}}"+" ( "+("{{vote.8.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.8.choice_set.all.0.count}}표"
    document.getElementById("18").innerHTML = "{{vote.8.choice_set.all.1}}"+" ( "+("{{vote.8.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.8.choice_set.all.1.count}}표"
    document.getElementById("19").innerHTML = "{{vote.9.choice_set.all.0}}"+" ( "+("{{vote.9.choice_set.all.0.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.9.choice_set.all.0.count}}표"
    document.getElementById("20").innerHTML = "{{vote.9.choice_set.all.1}}"+" ( "+("{{vote.9.choice_set.all.1.count}}"/"{{total_voted_number}}"*100).toFixed(2)+"% )"+"<br>{{vote.9.choice_set.all.1.count}}표"

</script>

polls/templates/polls/index.html
deploy 성공

polls/templates/start.html
{% load static %}
<!--링크 클릭하자 마자 보이는 화면-->
<html>

<head>
    <link href="static/css/start.css?after" type="text/css" rel="stylesheet">
    <link href="static/css/style.css" type="text/css" rel="stylesheet">  
    <script src="https://kit.fontawesome.com/105dacfb44.js" crossorigin="anonymous"></script>
</head>

<body onload="voteCheck()">
    <div>
    <div class="nav">
        <a href="{% url 'start_page' %}">
            <img src="{% static 'images/logo3.png' %}" width="240px" ; height="95px" ;>
    </div>
    <div class="total_voted_num" style="display:none;">
        {{total_voted_number}}
    </div>
    <div class="total_voted_number" value="{{total_voted_number}}">
        <!--현재 투표한 인원나타낼 div-->
    </div>
    <div class="count_num"></div>
    <br>
    <div class="image blinking">
        <img src="/static/images/logo3.png" class="logo" alt="No image" width="800px">
    </div>
    <br>
    <div class = "voteimpossible" style="    text-shadow: 2px 2px 6px #c9c9c9;
    color:#faff00;">투표는 하루에 한번만 가능합니다.</div>
    <div class="votepossible">
        <div class="box" id="vote">
            <a href="{% url 'vote_page' %}">
                <h1>투표하러 가기</h1>
            </a>
        </div>
    </div>
    <div class="box" id="new">
        <a href="{% url 'main_page' %}">
            <h1>실시간 투표 현황 보러가기</h1>
        </a>
    </div>

    <br>
</div>
</body>
</html>
<footer style="text-align: center; color:rgb(72, 72, 60);">
    © 2022 sogangsisters@gmail.com<br><br><br>
    <a href = "https://www.instagram.com/likelion_sg"><img src="/static/images/sg.png" style="color: darkgray;" width="50" height="50"></a>
    
    <a href = "https://www.instagram.com/likelion_ds"><img src="/static/images/ds.png"  width="50" height="50"></a>

    <!-- <a href = "https://www.instagram.com/likelion_sg/"><i style="color:#faff00" class="fab fa-instagram"></i></a>
    <a href = "https://www.instagram.com/likelion_sg/"><i style="color:#faff00" class="fab fa-instagram"></i></a> -->
    </footer>
    <br><br>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
    console.log(getCookie("isVoted"))

    // 쿠키 가져오는 함수
    function getCookie(cookieName) {
        var cookieValue = null;
        if (document.cookie) {
            var array = document.cookie.split((escape(cookieName) + '='));
            if (array.length >= 2) {
                var arraySub = array[1].split(';');
                cookieValue = unescape(arraySub[0]);
            }
        }
        return cookieValue;
    }
    // 투표 판별, 했으면 true, 안했으면 false
    window.onload =function voteCheck() {
        var voting = document.getElementsByClassName("votepossible")[0];
        var voted = document.getElementsByClassName("voteimpossible")[0];
        if (getCookie("isVoted") == null) {
            //투표 가능하도록
            voting.style.display = 'block';
            voted.style.display = 'none';
            console.log("재투표가능");
        } else {
            voting.style.display = 'none';
            voted.style.display = 'block';
            console.log("재투표불가");
        }
    } 
var today = new Date();

var year = today.getFullYear();
var month = ('0' + (today.getMonth() + 1)).slice(-2);
var day = ('0' + today.getDate()).slice(-2);

var dateString = year + '년 ' + month  + '월' + day + "일";

voted_num = document.getElementsByClassName("total_voted_num")[0].innerHTML

var defaulttxt = " 누적 투표인원은 "
// var text = "my line1 \nMyline 2";
// $('#dialog').html(text.replace("\n", "<br>"));

$({ val : 0 }).animate({ val : voted_num }, {
    duration: 1500,
    step: function() {
      var num = numberWithCommas(Math.floor(this.val));
      $(".total_voted_number").text(dateString+defaulttxt + num + "명입니다.");
    },
    complete: function() {
      var num = numberWithCommas(Math.floor(this.val));
      $(".total_voted_number").text(dateString+defaulttxt + num + "명입니다.");
    }
  });
  
  function numberWithCommas(x) {
      return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }
var today = new Date();
var year = today.getFullYear();
var month = ('0' + (today.getMonth() + 1)).slice(-2);
var day = ('0' + today.getDate()).slice(-2);

var dateString = year + '년' + month  + '월' + day + "일";

</script>